'use strict';

/**
 * Standard API error codes used across the system.
 * This should be kept in sync between the backend and frontend.
 */
const ApiErrorType = {
  // Common codes
  VALIDATION_FAILURE: 'VALIDATION_FAILURE',
  WRONG_CREDENTIALS: 'WRONG_CREDENTIALS',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  RECORD_NOT_SAVED: 'RECORD_NOT_SAVED',
  RECORD_SAVE_FAILURE: 'RECORD_SAVE_FAILURE',
  APPLICATION_ERROR: 'APPLICATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  LOGIN_REQUIRED: 'LOGIN_REQUIRED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',

  // Additional codes from appErrorHandlers
  RECORD_EXIST: 'RECORD_EXIST',
  UPDATE_FAILED: 'UPDATE_FAILED',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  USED_TOKEN: 'USED_TOKEN',
  BAD_VISITOR_TOKEN: 'BAD_VISITOR_TOKEN',
  FILE_FORMAT_NOT_SUPPORTED: 'FILE_FORMAT_NOT_SUPPORTED',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  BAD_INPUT: 'BAD_INPUT',
  INPUT_NOT_UUID: 'INPUT_NOT_UUID',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_TIME_VALUE: 'INVALID_TIME_VALUE',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  PARSE_ERROR: 'PARSE_ERROR'
};

module.exports = {
  ApiErrorType
};
